version: '2'

services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - /code/node_modules
