version: '2'

services:
  db:
    image: mariadb:10
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/model/library-network.sql:/docker-entrypoint-initdb.d/1.ddl-schema.sql
      - ./src/model/books.sql:/docker-entrypoint-initdb.d/2.books.sql
  redis:
    image: redis:6
    env_file:
      - ./.env
    ports:
      - 6379:6379
volumes: 
  mysql-data: