version: '2'

services:
  web-dev:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - /code/node_modules
    command: npm run debug
  db:
    restart: always
    image: mariadb:10
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/model/ddl-schema.sql:/docker-entrypoint-initdb.d/1.ddl-schema.sql
      - ./src/model/init-data.sql:/docker-entrypoint-initdb.d/2.init-data.sql
      # - ./src/model/books.sql:/docker-entrypoint-initdb.d/3.books.sql
  redis:
    restart: always
    image: redis:6
    env_file:
      - ./.env
    ports:
      - 6379:6379
volumes: 
  mysql-data-dev: