version: "3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
     - 80:80
      # - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs/:/etc/ssl/private
    extra_hosts:
      - host.docker.internal:host-gateway
